name: Continuous Integration

on:
  pull_request:
    paths-ignore:
      - .github/*
      - .gitignore
      - README.md

jobs:
  ci_linux-64:
    name: linux-64 CI
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        environment: ["r43", "r44"]

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Copy TOML
        run: |
          mkdir /tmp/pixi
          cp ${GITHUB_WORKSPACE}/pixi.toml /tmp/pixi

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false

      - name: Run unit tests
        run: pixi run --environment ${{ matrix.environment }} --manifest-path /tmp/pixi/pixi.toml devtools_test

      - name: Run R CMD CHECK
        run: |
          pixi run --environment ${{ matrix.environment }} --manifest-path /tmp/pixi/pixi.toml build
          pixi run --environment ${{ matrix.environment }} --manifest-path /tmp/pixi/pixi.toml rcmdcheck

      - name: Check unit test code coverage
        if: ${{ matrix.environment == 'r44' }}
        run: pixi run --environment ${{ matrix.environment }} --manifest-path /tmp/pixi/pixi.toml codecov

  ci_osx-arm64:
    name: osx-arm64 CI
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        environment: ["r43", "r44"]
    
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Copy TOML
        run: |
          mkdir /tmp/pixi
          cp ${GITHUB_WORKSPACE}/pixi.toml /tmp/pixi

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false

      - name: Run unit tests
        run: pixi run --environment ${{ matrix.environment }} --manifest-path /tmp/pixi/pixi.toml devtools_test

      - name: Run R CMD CHECK
        run: |
          pixi run --environment ${{ matrix.environment }} --manifest-path /tmp/pixi/pixi.toml build
          pixi run --environment ${{ matrix.environment }} --manifest-path /tmp/pixi/pixi.toml rcmdcheck
