name: R-CMD-check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create TOML from recipe  
        run: .github/workflows/create_toml_from_yaml.sh

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.0

      - name: Session info
        run: pixi run -e r44 R -e 'sessionInfo()'

      - name: Install missing packages
        run: pixi run -e r44 install_missing_packages

      - name: Build package
        run: pixi run -e r44 build

      - name: Check package
        run: pixi run -e r44 rcmdcheck