on:
  push:
    branches: [main, master]
  pull_request:

name: test_coverage

jobs:
  update_coverage_badge:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - name: Checkout master
        uses: actions/checkout@v5
        with:
          ref: master

      - name: Create TOML from recipe
        run: .github/workflows/create_toml_from_yaml.sh ${GITHUB_WORKSPACE}

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.1

      - name: Check unit test code coverage
        run: pixi run codecov
